---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(DT)
```

```{r}
Sys.getlocale()
Sys.setlocale("LC_ALL","C")
rd <- read.csv("./seoul_roadaccident.csv", header=TRUE, encoding = "UTF-8")
Sys.setlocale("LC_ALL","Korean")
rd
```

```{r}
# 데이터 na값 제거
colnames(rd)[1:5] <- c('합계', '자치구', '사고유형', '소계', '사고통계')
names(rd) <- gsub("X", "", names(rd))
rd
# pivotlonger
rd <- rd %>% pivot_longer(cols = c(`1988`: `2021`), 
                    names_to = "year",
                    values_to = "case")
```


```{r}
rd$자치구 <- str_replace(rd$자치구, "소계", "서울시")
rd <- rd %>% filter(year >= 2007)
# 나머지 - 들은 사고건수가 0건임으로 이를 0으로 대체
rd$case <- str_replace(rd$case, "-", "0")
rd$case <- as.double(rd$case)

colSums(is.na(rd))
names(which(is.na(rd$case)))
# 결측값이 존재하지 않는다
```

```{r}
DT::datatable(rd)
```


```{r}
rd_case <- rd %>% 
  filter(사고통계 == "발생건수 (건)"& !자치구 == "서울특별시") %>% 
  ggplot(aes(x=year, y=case, color=자치구, group=자치구)) +
  geom_line() +
  facet_wrap(~c(사고유형))

rd_dead <- rd %>% 
  filter(사고통계 == "사망자수 (명)") %>% 
  ggplot(aes(x=year, y=case, color=자치구, group=자치구)) +
  geom_line() +
  facet_wrap(~c(사고유형))

rd_casualty <- rd %>% 
  filter(사고통계 == "부상자수 (명)"& !자치구 == "서울특별시") %>% 
  ggplot(aes(x=year, y=case, color=자치구, group=자치구)) +
  geom_line() +
  facet_wrap(~c(사고유형))

rd_case
rd_dead
rd_casualty
```


## tidy in english version
```{r}
rd_e <- rd[, c(-1,-4)]
colnames(rd_e)[1:3] <- c("district", "category", "harm")
unique(rd_e$district)
```


```{r}
district_name <- unique(rd_e$district)
district_code <- c("seoul", "jong", "jungg", "yong", 
                   "sungd", "gwang", "dongd", "jungr", 
                   "sungb", "gangb", "dob", "now", 
                   "eun", "seod", "ma", 
                   "yang", "gangs", "gur", "gum", 
                   "yeong", "dongj", "gwan", 
                   "seo", "gangn", "song", "gangd") 
```


```{r}
# 영어로 표현 바꾸기
rd_eng <- rd_e %>% transmute(district, 
                             category = recode(category, "합계" = "total",
                                               "차대사람" = "CtoP",
                                               "차대차" ="CtoC",
                                               "차량단독" = "CarOnly"),
                             harm = recode(harm, "발생건수 (건)" ="totalcase",
                                           "사망자수 (명)"="death",
                                           "부상자수 (명)"="injured"),
                             year, case)
rd_eng$district <- district_code[match(rd_e$district, district_name)]
```


```{r}
rd1 <- rd_eng %>% pivot_wider(names_from = year, values_from = case)
```

```{r}
write.csv(rd, "./road_accident.csv", row.names=F, fileEncoding = 'cp949')
write.csv(rd1, "./road_accident_data.csv", row.names=F, fileEncoding = 'cp949')
```



